version: 2
updates:
- package-ecosystem: gradle
  directory: "/authcode"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework.boot
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.boot:spring-boot-starter-webflux
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.boot:spring-boot-starter-thymeleaf
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.boot:spring-boot-starter-web
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.security:spring-security-config
    versions:
    - 5.4.2
    - 5.4.4
    - 5.4.5
  - dependency-name: org.springframework.security:spring-security-oauth2-jose
    versions:
    - 5.4.2
    - 5.4.4
    - 5.4.5
  - dependency-name: org.springframework.security:spring-security-oauth2-client
    versions:
    - 5.4.2
    - 5.4.4
    - 5.4.5
  - dependency-name: io.pivotal.cfenv:java-cfenv-boot-pivotal-sso
    versions:
    - 2.2.5.RELEASE
- package-ecosystem: gradle
  directory: "/authcode-client-credentials"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework.boot:spring-boot-starter-webflux
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.boot:spring-boot-starter-thymeleaf
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.boot:spring-boot-starter-web
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.boot
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.security:spring-security-config
    versions:
    - 5.4.2
    - 5.4.4
    - 5.4.5
  - dependency-name: org.springframework.security:spring-security-oauth2-jose
    versions:
    - 5.4.2
    - 5.4.4
    - 5.4.5
  - dependency-name: org.springframework.security:spring-security-oauth2-client
    versions:
    - 5.4.2
    - 5.4.4
    - 5.4.5
  - dependency-name: io.pivotal.cfenv:java-cfenv-boot-pivotal-sso
    versions:
    - 2.2.5.RELEASE
- package-ecosystem: gradle
  directory: "/client-credentials"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework.boot
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.boot:spring-boot-starter-webflux
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.boot:spring-boot-starter-thymeleaf
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.boot:spring-boot-starter-web
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.security:spring-security-config
    versions:
    - 5.4.2
    - 5.4.4
    - 5.4.5
  - dependency-name: org.springframework.security:spring-security-oauth2-jose
    versions:
    - 5.4.2
    - 5.4.4
    - 5.4.5
  - dependency-name: org.springframework.security:spring-security-oauth2-client
    versions:
    - 5.4.2
    - 5.4.4
    - 5.4.5
  - dependency-name: io.pivotal.cfenv:java-cfenv-boot-pivotal-sso
    versions:
    - 2.2.5.RELEASE
- package-ecosystem: gradle
  directory: "/resource-server"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework.boot:spring-boot-starter-web
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.boot
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.security:spring-security-config
    versions:
    - 5.4.2
    - 5.4.4
    - 5.4.5
  - dependency-name: org.springframework.security:spring-security-oauth2-jose
    versions:
    - 5.4.2
    - 5.4.4
    - 5.4.5
  - dependency-name: org.springframework.security:spring-security-oauth2-resource-server
    versions:
    - 5.4.2
    - 5.4.4
    - 5.4.5
- package-ecosystem: gradle
  directory: "/journeys"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.fasterxml.jackson.core:jackson-core
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.core:jackson-databind
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.core:jackson-annotations
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: org.fluentlenium:fluentlenium-assertj
    versions:
    - 4.6.0
  - dependency-name: org.fluentlenium:fluentlenium-junit
    versions:
    - 4.6.0
