plugins {
	id 'org.springframework.boot' version '4.1.1'
	id 'io.spring.dependency-management' version '1.1.6'
	id 'java'
}



group = 'io.pivotal.identityService'
sourceCompatibility = '21'

ext {
	springVersion = '4.1.1'
	springSecurityVersion = '5.3.4.RELEASE'
}

repositories {
	mavenCentral()
}

dependencies {
	implementation "org.springframework.boot:spring-boot-starter-web"
	implementation "org.springframework.security:spring-security-oauth2-resource-server"
	implementation "org.springframework.security:spring-security-oauth2-jose"
	implementation "org.springframework.security:spring-security-config"
}
