plugins {
	id 'org.springframework.boot' version '3.5.12'
	id 'java'
}

apply plugin: 'io.spring.dependency-management'

group = 'io.pivotal.identityService'
sourceCompatibility = '17'

ext {
	springVersion = '3.5.12'
	springSecurityVersion = '6.5.9'
}

repositories {
	mavenCentral()
}

dependencies {
	implementation "org.springframework.boot:spring-boot-starter-web:$springVersion"
	implementation "org.springframework.security:spring-security-oauth2-resource-server:$springSecurityVersion"
	implementation "org.springframework.security:spring-security-oauth2-jose:$springSecurityVersion"
	implementation "org.springframework.security:spring-security-config:$springSecurityVersion"
}
