plugins {
	id 'org.springframework.boot' version '4.1.1'
	id 'io.spring.dependency-management' version '1.1.6'
	id 'java'
}



group = 'io.pivotal.identityService'
sourceCompatibility = '21'

ext {
	springVersion = '4.1.1'
	springSecurityVersion = '5.3.4.RELEASE'
	cfEnvSsoVersion = '4.0.0'
	cfCertificateTrusterVersion = '1.0.1.RELEASE'
	useCfCertificateTruster = false // set this property to true when cert trusting is required
}

repositories {
	mavenCentral()
}

dependencies {
	implementation "org.springframework.boot:spring-boot-starter-web"
	implementation "org.springframework.boot:spring-boot-starter-thymeleaf"
	implementation "org.springframework.boot:spring-boot-starter-webflux"
	implementation "org.springframework.security:spring-security-oauth2-client"
	implementation "org.springframework.security:spring-security-oauth2-jose"
	implementation "org.springframework.security:spring-security-config"
	implementation "io.pivotal.cfenv:java-cfenv-boot-pivotal-sso:$cfEnvSsoVersion"
	if (useCfCertificateTruster) {
		implementation "io.pivotal.spring.cloud:cloudfoundry-certificate-truster:$cfCertificateTrusterVersion"
	}
}